spring:
  application:
    name: seckill-business
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: ubuntu.fun:8848
  redis:
    host: localhost
    port: 6379
dubbo:
  scan:
    base-packages: fun.hara.mall.seckill.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://ubuntu.fun
    port: 8848
server:
  # ${random.int[9000,9999]} 随机端口
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: "*"