spring:
  application:
    name: order-business
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: ubuntu.fun:8848
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  redis:
    host: localhost
    port: 6379
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mall_seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
      username: root
      password: 123456
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
dubbo:
  scan:
    base-packages: fun.hara.mall.order.consumer
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://ubuntu.fun
    port: 8848

  redis:
    host: localhost
    port: 6379
#security:
#  oauth2:
#    client:
#      client-id: client
#      client-secret: secret
#      access-token-uri: http://localhost:9000/oauth/token
#      user-authorization-uri: http://localhost:9000/oauth/authorize
#    resource:
#      token-info-uri: http://localhost:9000/oauth/check_token
server:
  # ${random.int[9000,9999]} 随机端口
  port: 9003
management:
  endpoints:
    web:
      exposure:
        include: "*"
rocketmq:
  name-server: rmq.fun:9876
